### ISSUE TITLE
Roadmap for 2020 Spring

### ISSUE THREAD

**Issue by zaki-yama** [kintone/js-sdk#106]
This plan is a roadmap for the next few months.
We focus on supporting all features that [kintone-js-sdk](https://github.com/kintone/kintone-js-sdk) has.

## Plan Items

- [x] addAllRecords (#102)
- [x] updateAllRecords (#103)
- [x] deleteAllRecords (#104)
- [x] upsert single record (#105)
- [x] support client certificate (#113)
- [x] support OAuth bearer token header (#110)
- [x] support Proxy server (#114)
- [x] support file path in `uploadFile()` method (#115)
- [x] ✋ ~upsert multiple records~
- [x] support UserAgent in Node environment

🏃 ... work in progress
🤔  ... under discussion
✋  ... postpone

**Comment by r3-yamauchi** [comment]
Why not use GitHub's 'Projects' feature?
https://github.com/kintone/js-sdk/projects

**Comment by koba04** [comment]
@r3-yamauchi 
We've considered using GitHub Projects or Milestone to share our roadmap, but currently, we don't have many items for the roadmap.
So sharing the roadmap through an issue is enough for us. This also makes it possible to discuss the roadmap on issue comments.

We might consider using GitHub Projects or Milestone in the future.
Thank you!

**Comment by koba04** [comment]
We've completed all issues in the roadmap except "upsert multiple records."
The feature is in progress; however, there are some issues we have to solve so that it exposes as a public API.

This postponement doesn't mean we never add this feature. We would work on it in the future.
