### ISSUE TITLE
Roadmap for 2020 Summer

### ISSUE THREAD

**Issue by shintaroNagata** [kintone/js-sdk#258]
This plan is a roadmap for the next few months.
We will introduce item details in each issue.

## Plan Items
- [x] ~⚠️~ support `x-cybozu-warning` header (#67)
- [x] provide type definitions for each field type
- [ ] ✋ ~add a feature like [config-helper](https://github.com/kintone/config-helper) that retrieves app field information~

⚠️  … BREAKING CHANGE
🏃 ... work in progress
🤔  ... under discussion
✋  ... postpone

Japanese version: https://github.com/kintone/js-sdk-ja/issues/2
