### ISSUE TITLE
Unify environment variables used in js-sdk packages 

### ISSUE THREAD

**Issue by koba04** [kintone/js-sdk#530]
## Tasks

- [x] Add missing environment variables and CLI flags support in `@kintone/plugin-uploader`  @chick-p 
  - [x] `KINTONE_BASE_URL` #534
- [x] Add missing environment variables  and CLI flags support in `@kintone/customize-uploader` @chick-p 
  - [x] `KINTONE_BASE_URL` #543
  - [x] `KINTONE_OAUTH_TOKEN` #566
- [x] Add missing environment variables  and CLI flags support in `@kintone/dts-gen` @koba04 (@potaracom)
  - [x] `KINTONE_USERNAME` #532 (#458)
  - [x] `KINTONE_PASSWORD` #532 (#458)
  - [x] `KINTONE_BASE_URL` #536
  - [x] `KINTONE_API_TOKEN` #575
  - [x] `KINTONE_OAUTH_TOKEN` #575 
  - [x] `KINTONE_BASIC_AUTH_USERNAME` #532 (#458)
  - [x] `KINTONE_BASIC_AUTH_PASSWORD ` #532 (#458)
  - [x] `HTTP_PROXY` #585 
  - [x] `HTTPS_PROXY ` #585 
- [x] Release a minor version of the packages
- [x] Add deprecated warnings for the usage of `KINTONE_DOMAIN`, which includes `domain` option as well @chick-p 
  - [x] `@kintone/plugin-uploader` #697 
  - [x] `@kintone/customize-uploader` #602 
- [x] Add deprecated warnings for the usage of `host`, `proxyHost`, and `proxyPort` option
  - [x] `@kintone/dts-gen` #869
- [x] Release a minor version of the packages
  - [`@kintone/dts-gen@4.0.0`](https://github.com/kintone/js-sdk/blob/master/packages/dts-gen/CHANGELOG.md#400-2021-05-11)
  - [`@kintone/plugin-uploader@4.3.0`](https://github.com/kintone/js-sdk/blob/master/packages/plugin-uploader/CHANGELOG.md#430-2021-03-09)
  - `@kintone/customize-uploader@3.1.1` (No CHANGELOG)
- [x]  Remove deprecated environment variables and CLI flags from the packages.
  - [x] `@kintone/plugin-uploader` #1046
  - [x] `@kintone/customize-uploader` #1047 
  - [x] `@kintone/dts-gen` #1048
- [x]  Release a major version of the packages :tada:

## Package

- @kintone/dts-gen
- @kintone/customize-uploader
- @kintone/plugin-uploader

## Why

Currently, those packages have some environment variables support like `KINTONE_USERNAME` and `KINTONE_API_TOKEN`, which is useful but the support has some inconsistency like https://github.com/kintone/js-sdk-ja/issues/7#issuecomment-707065747 (Thank you @potaracom)

The inconsistency is cumbersome for developers who use these packages.
So we'd like to address the issue.

## What

We will unify the usage of environment variables like the following.

### Environment variables we use

- `KINTONE_USERNAME` ... Your user name
- `KINTONE_PASSWORD` ... Your password
- `KINTONE_BASE_URL` ... The URL of your Kintone environment e.g. https://example.kintone.com
- `KINTONE_API_TOKEN` ... API Token
- `KINTONE_OAUTH_TOKEN` ... OAuth Token
- `KINTONE_BASIC_AUTH_USERNAME` ... The user name of Basic Authentication
- `KINTONE_BASIC_AUTH_PASSWORD` ... The password of Basic Authentication
- `HTTP_PROXY` ... The URL of HTTP proxy server
- `HTTPS_PROXY` ... The URL of HTTPS proxy server

### Matrix of the environment variables and packages

|                             | plugin-uploader | customize-uploader | dts-gen    |
| --------------------------- | --------------- | ------------------ | ---------- |
| KINTONE_USERNAME            | :ok_woman:      | :ok_woman:         | :rocket:   |
| KINTONE_PASSWORD            | :ok_woman:      | :ok_woman:         | :rocket:   |
| KINTONE_BASE_URL            | :rocket:        | :rocket:           | :rocket:   |
| KINTONE_API_TOKEN           | :no_entry:      | :no_entry:         | :rocket:   |
| KINTONE_OAUTH_TOKEN         | :no_entry:      | :rocket:           | :rocket:   |
| KINTONE_DOMAIN              | :no_good:       | :no_good:          | :no_entry: |
| KINTONE_BASIC_AUTH_USERNAME | :ok_woman:      | :ok_woman:         | :rocket:   |
| KINTONE_BASIC_AUTH_PASSWORD | :ok_woman:      | :ok_woman:         | :rocket:   |
| HTTP_PROXY                  | :ok_woman:      | :ok_woman:         | :rocket:   |
| HTTPS_PROXY                 | :ok_woman:      | :ok_woman:         | :rocket:   |

- :ok_woman: Already supported
- :rocket: Will be supported in this issue
- :no_entry: Won't be supported because of limitations of Kintone
- :no_good: Will be removed in this issue

## Adoption strategy

1. Add missing environment variable support, which includes CLI options if required.
1. Release a minor version of the packages
1. Add deprecated warnings for the usage of `KINTONE_DOMAIN`, which includes `domain` option as well.
1. Release a minor version of the packages
1. Remove deprecated environment variables and CLI flags from the packages.
1. Release a major version of the packages

**Comment by mshrtsr** [comment]
All tasks in this issue have been done!
Thank you to all contributors!!
